services:
  postgres:
    image: postgres:16-alpine
    container_name: nutrisoftware_db
    environment:
      POSTGRES_DB: nutrisoftware
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nutrisoftware_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
